// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STYLESHEETV2_STYLESV2_H_
#define FLATBUFFERS_GENERATED_STYLESHEETV2_STYLESV2_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace StylesV2 {

struct PoolString;
struct PoolStringBuilder;

struct Integer;
struct IntegerBuilder;

struct Double;
struct DoubleBuilder;

struct Boolean;
struct BooleanBuilder;

struct StringArray;
struct StringArrayBuilder;

struct IntegerArray;
struct IntegerArrayBuilder;

struct DoubleArray;
struct DoubleArrayBuilder;

struct ObjectArray;
struct ObjectArrayBuilder;

struct IntegereArrayArray;
struct IntegereArrayArrayBuilder;

struct DoubleArrayArray;
struct DoubleArrayArrayBuilder;

struct KeyValue;
struct KeyValueBuilder;

struct Object;
struct ObjectBuilder;

struct DeclarationTuple;
struct DeclarationTupleBuilder;

struct Selector;

struct PseudoKey;

struct KeyValueString;

struct Style;
struct StyleBuilder;

struct Font;
struct FontBuilder;

struct KeyframeAnimationPoint;
struct KeyframeAnimationPointBuilder;

struct KeyframeAnimation;
struct KeyframeAnimationBuilder;

struct PrimitiveCondition;
struct PrimitiveConditionBuilder;

struct CompoundCondition;
struct CompoundConditionBuilder;

struct Condition;
struct ConditionBuilder;

struct Media;
struct MediaBuilder;

struct StyleSheet;
struct StyleSheetBuilder;

enum Value : uint8_t {
  Value_NONE = 0,
  Value_PoolString = 1,
  Value_Integer = 2,
  Value_Double = 3,
  Value_Boolean = 4,
  Value_StringArray = 5,
  Value_IntegerArray = 6,
  Value_DoubleArray = 7,
  Value_Object = 8,
  Value_ObjectArray = 9,
  Value_IntegereArrayArray = 10,
  Value_DoubleArrayArray = 11,
  Value_MIN = Value_NONE,
  Value_MAX = Value_DoubleArrayArray
};

inline const Value (&EnumValuesValue())[12] {
  static const Value values[] = {
    Value_NONE,
    Value_PoolString,
    Value_Integer,
    Value_Double,
    Value_Boolean,
    Value_StringArray,
    Value_IntegerArray,
    Value_DoubleArray,
    Value_Object,
    Value_ObjectArray,
    Value_IntegereArrayArray,
    Value_DoubleArrayArray
  };
  return values;
}

inline const char * const *EnumNamesValue() {
  static const char * const names[13] = {
    "NONE",
    "PoolString",
    "Integer",
    "Double",
    "Boolean",
    "StringArray",
    "IntegerArray",
    "DoubleArray",
    "Object",
    "ObjectArray",
    "IntegereArrayArray",
    "DoubleArrayArray",
    nullptr
  };
  return names;
}

inline const char *EnumNameValue(Value e) {
  if (::flatbuffers::IsOutRange(e, Value_NONE, Value_DoubleArrayArray)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValue()[index];
}

template<typename T> struct ValueTraits {
  static const Value enum_value = Value_NONE;
};

template<> struct ValueTraits<StylesV2::PoolString> {
  static const Value enum_value = Value_PoolString;
};

template<> struct ValueTraits<StylesV2::Integer> {
  static const Value enum_value = Value_Integer;
};

template<> struct ValueTraits<StylesV2::Double> {
  static const Value enum_value = Value_Double;
};

template<> struct ValueTraits<StylesV2::Boolean> {
  static const Value enum_value = Value_Boolean;
};

template<> struct ValueTraits<StylesV2::StringArray> {
  static const Value enum_value = Value_StringArray;
};

template<> struct ValueTraits<StylesV2::IntegerArray> {
  static const Value enum_value = Value_IntegerArray;
};

template<> struct ValueTraits<StylesV2::DoubleArray> {
  static const Value enum_value = Value_DoubleArray;
};

template<> struct ValueTraits<StylesV2::Object> {
  static const Value enum_value = Value_Object;
};

template<> struct ValueTraits<StylesV2::ObjectArray> {
  static const Value enum_value = Value_ObjectArray;
};

template<> struct ValueTraits<StylesV2::IntegereArrayArray> {
  static const Value enum_value = Value_IntegereArrayArray;
};

template<> struct ValueTraits<StylesV2::DoubleArrayArray> {
  static const Value enum_value = Value_DoubleArrayArray;
};

bool VerifyValue(::flatbuffers::Verifier &verifier, const void *obj, Value type);
bool VerifyValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum ConditionValue : uint8_t {
  ConditionValue_NONE = 0,
  ConditionValue_PrimitiveCondition = 1,
  ConditionValue_CompoundCondition = 2,
  ConditionValue_MIN = ConditionValue_NONE,
  ConditionValue_MAX = ConditionValue_CompoundCondition
};

inline const ConditionValue (&EnumValuesConditionValue())[3] {
  static const ConditionValue values[] = {
    ConditionValue_NONE,
    ConditionValue_PrimitiveCondition,
    ConditionValue_CompoundCondition
  };
  return values;
}

inline const char * const *EnumNamesConditionValue() {
  static const char * const names[4] = {
    "NONE",
    "PrimitiveCondition",
    "CompoundCondition",
    nullptr
  };
  return names;
}

inline const char *EnumNameConditionValue(ConditionValue e) {
  if (::flatbuffers::IsOutRange(e, ConditionValue_NONE, ConditionValue_CompoundCondition)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConditionValue()[index];
}

template<typename T> struct ConditionValueTraits {
  static const ConditionValue enum_value = ConditionValue_NONE;
};

template<> struct ConditionValueTraits<StylesV2::PrimitiveCondition> {
  static const ConditionValue enum_value = ConditionValue_PrimitiveCondition;
};

template<> struct ConditionValueTraits<StylesV2::CompoundCondition> {
  static const ConditionValue enum_value = ConditionValue_CompoundCondition;
};

bool VerifyConditionValue(::flatbuffers::Verifier &verifier, const void *obj, ConditionValue type);
bool VerifyConditionValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Selector FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t string_id_;
  uint8_t integer_value_;
  uint8_t is_string_;
  int16_t padding0__;

 public:
  Selector()
      : string_id_(0),
        integer_value_(0),
        is_string_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Selector(uint32_t _string_id, uint8_t _integer_value, bool _is_string)
      : string_id_(::flatbuffers::EndianScalar(_string_id)),
        integer_value_(::flatbuffers::EndianScalar(_integer_value)),
        is_string_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_is_string))),
        padding0__(0) {
    (void)padding0__;
  }
  uint32_t string_id() const {
    return ::flatbuffers::EndianScalar(string_id_);
  }
  uint8_t integer_value() const {
    return ::flatbuffers::EndianScalar(integer_value_);
  }
  bool is_string() const {
    return ::flatbuffers::EndianScalar(is_string_) != 0;
  }
};
FLATBUFFERS_STRUCT_END(Selector, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) PseudoKey FLATBUFFERS_FINAL_CLASS {
 private:
  int8_t integer_value_;
  uint8_t bool_value_;
  uint8_t is_int_;

 public:
  PseudoKey()
      : integer_value_(0),
        bool_value_(0),
        is_int_(0) {
  }
  PseudoKey(int8_t _integer_value, bool _bool_value, bool _is_int)
      : integer_value_(::flatbuffers::EndianScalar(_integer_value)),
        bool_value_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_bool_value))),
        is_int_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_is_int))) {
  }
  int8_t integer_value() const {
    return ::flatbuffers::EndianScalar(integer_value_);
  }
  bool bool_value() const {
    return ::flatbuffers::EndianScalar(bool_value_) != 0;
  }
  bool is_int() const {
    return ::flatbuffers::EndianScalar(is_int_) != 0;
  }
};
FLATBUFFERS_STRUCT_END(PseudoKey, 3);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KeyValueString FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t key_;
  uint32_t value_;

 public:
  KeyValueString()
      : key_(0),
        value_(0) {
  }
  KeyValueString(uint32_t _key, uint32_t _value)
      : key_(::flatbuffers::EndianScalar(_key)),
        value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t key() const {
    return ::flatbuffers::EndianScalar(key_);
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(KeyValueString, 8);

struct PoolString FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PoolStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct PoolStringBuilder {
  typedef PoolString Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(PoolString::VT_ID, id, 0);
  }
  explicit PoolStringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PoolString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PoolString>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PoolString> CreatePoolString(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  PoolStringBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Integer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntegerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int64_t value() const {
    return GetField<int64_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct IntegerBuilder {
  typedef Integer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(int64_t value) {
    fbb_.AddElement<int64_t>(Integer::VT_VALUE, value, 0);
  }
  explicit IntegerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Integer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Integer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Integer> CreateInteger(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t value = 0) {
  IntegerBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Double FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DoubleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct DoubleBuilder {
  typedef Double Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(Double::VT_VALUE, value, 0.0);
  }
  explicit DoubleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Double> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Double>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Double> CreateDouble(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  DoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Boolean FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BooleanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct BooleanBuilder {
  typedef Boolean Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(Boolean::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit BooleanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Boolean> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Boolean>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Boolean> CreateBoolean(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool value = false) {
  BooleanBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct StringArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint32_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct StringArrayBuilder {
  typedef StringArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values) {
    fbb_.AddOffset(StringArray::VT_VALUES, values);
  }
  explicit StringArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringArray> CreateStringArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values = 0) {
  StringArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringArray> CreateStringArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint32_t>(*values) : 0;
  return StylesV2::CreateStringArray(
      _fbb,
      values__);
}

struct IntegerArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntegerArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<int64_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct IntegerArrayBuilder {
  typedef IntegerArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values) {
    fbb_.AddOffset(IntegerArray::VT_VALUES, values);
  }
  explicit IntegerArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IntegerArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IntegerArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IntegerArray> CreateIntegerArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values = 0) {
  IntegerArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IntegerArray> CreateIntegerArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<int64_t>(*values) : 0;
  return StylesV2::CreateIntegerArray(
      _fbb,
      values__);
}

struct DoubleArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DoubleArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<double> *values() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct DoubleArrayBuilder {
  typedef DoubleArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<double>> values) {
    fbb_.AddOffset(DoubleArray::VT_VALUES, values);
  }
  explicit DoubleArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DoubleArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DoubleArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DoubleArray> CreateDoubleArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> values = 0) {
  DoubleArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DoubleArray> CreateDoubleArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<double>(*values) : 0;
  return StylesV2::CreateDoubleArray(
      _fbb,
      values__);
}

struct ObjectArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ObjectArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.VerifyVectorOfTables(values()) &&
           verifier.EndTable();
  }
};

struct ObjectArrayBuilder {
  typedef ObjectArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>>> values) {
    fbb_.AddOffset(ObjectArray::VT_VALUES, values);
  }
  explicit ObjectArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ObjectArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ObjectArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ObjectArray> CreateObjectArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>>> values = 0) {
  ObjectArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ObjectArray> CreateObjectArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::KeyValue>> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::KeyValue>>(*values) : 0;
  return StylesV2::CreateObjectArray(
      _fbb,
      values__);
}

struct IntegereArrayArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntegereArrayArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::IntegerArray>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::IntegerArray>> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.VerifyVectorOfTables(values()) &&
           verifier.EndTable();
  }
};

struct IntegereArrayArrayBuilder {
  typedef IntegereArrayArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::IntegerArray>>> values) {
    fbb_.AddOffset(IntegereArrayArray::VT_VALUES, values);
  }
  explicit IntegereArrayArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IntegereArrayArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IntegereArrayArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IntegereArrayArray> CreateIntegereArrayArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::IntegerArray>>> values = 0) {
  IntegereArrayArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IntegereArrayArray> CreateIntegereArrayArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::IntegerArray>> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::IntegerArray>>(*values) : 0;
  return StylesV2::CreateIntegereArrayArray(
      _fbb,
      values__);
}

struct DoubleArrayArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DoubleArrayArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DoubleArray>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DoubleArray>> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.VerifyVectorOfTables(values()) &&
           verifier.EndTable();
  }
};

struct DoubleArrayArrayBuilder {
  typedef DoubleArrayArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DoubleArray>>> values) {
    fbb_.AddOffset(DoubleArrayArray::VT_VALUES, values);
  }
  explicit DoubleArrayArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DoubleArrayArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DoubleArrayArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DoubleArrayArray> CreateDoubleArrayArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DoubleArray>>> values = 0) {
  DoubleArrayArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DoubleArrayArray> CreateDoubleArrayArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::DoubleArray>> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::DoubleArray>>(*values) : 0;
  return StylesV2::CreateDoubleArrayArray(
      _fbb,
      values__);
}

struct KeyValue FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyValueBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  StylesV2::Value value_type() const {
    return static_cast<StylesV2::Value>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const StylesV2::PoolString *value_as_PoolString() const {
    return value_type() == StylesV2::Value_PoolString ? static_cast<const StylesV2::PoolString *>(value()) : nullptr;
  }
  const StylesV2::Integer *value_as_Integer() const {
    return value_type() == StylesV2::Value_Integer ? static_cast<const StylesV2::Integer *>(value()) : nullptr;
  }
  const StylesV2::Double *value_as_Double() const {
    return value_type() == StylesV2::Value_Double ? static_cast<const StylesV2::Double *>(value()) : nullptr;
  }
  const StylesV2::Boolean *value_as_Boolean() const {
    return value_type() == StylesV2::Value_Boolean ? static_cast<const StylesV2::Boolean *>(value()) : nullptr;
  }
  const StylesV2::StringArray *value_as_StringArray() const {
    return value_type() == StylesV2::Value_StringArray ? static_cast<const StylesV2::StringArray *>(value()) : nullptr;
  }
  const StylesV2::IntegerArray *value_as_IntegerArray() const {
    return value_type() == StylesV2::Value_IntegerArray ? static_cast<const StylesV2::IntegerArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArray *value_as_DoubleArray() const {
    return value_type() == StylesV2::Value_DoubleArray ? static_cast<const StylesV2::DoubleArray *>(value()) : nullptr;
  }
  const StylesV2::Object *value_as_Object() const {
    return value_type() == StylesV2::Value_Object ? static_cast<const StylesV2::Object *>(value()) : nullptr;
  }
  const StylesV2::ObjectArray *value_as_ObjectArray() const {
    return value_type() == StylesV2::Value_ObjectArray ? static_cast<const StylesV2::ObjectArray *>(value()) : nullptr;
  }
  const StylesV2::IntegereArrayArray *value_as_IntegereArrayArray() const {
    return value_type() == StylesV2::Value_IntegereArrayArray ? static_cast<const StylesV2::IntegereArrayArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArrayArray *value_as_DoubleArrayArray() const {
    return value_type() == StylesV2::Value_DoubleArrayArray ? static_cast<const StylesV2::DoubleArrayArray *>(value()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const StylesV2::PoolString *KeyValue::value_as<StylesV2::PoolString>() const {
  return value_as_PoolString();
}

template<> inline const StylesV2::Integer *KeyValue::value_as<StylesV2::Integer>() const {
  return value_as_Integer();
}

template<> inline const StylesV2::Double *KeyValue::value_as<StylesV2::Double>() const {
  return value_as_Double();
}

template<> inline const StylesV2::Boolean *KeyValue::value_as<StylesV2::Boolean>() const {
  return value_as_Boolean();
}

template<> inline const StylesV2::StringArray *KeyValue::value_as<StylesV2::StringArray>() const {
  return value_as_StringArray();
}

template<> inline const StylesV2::IntegerArray *KeyValue::value_as<StylesV2::IntegerArray>() const {
  return value_as_IntegerArray();
}

template<> inline const StylesV2::DoubleArray *KeyValue::value_as<StylesV2::DoubleArray>() const {
  return value_as_DoubleArray();
}

template<> inline const StylesV2::Object *KeyValue::value_as<StylesV2::Object>() const {
  return value_as_Object();
}

template<> inline const StylesV2::ObjectArray *KeyValue::value_as<StylesV2::ObjectArray>() const {
  return value_as_ObjectArray();
}

template<> inline const StylesV2::IntegereArrayArray *KeyValue::value_as<StylesV2::IntegereArrayArray>() const {
  return value_as_IntegereArrayArray();
}

template<> inline const StylesV2::DoubleArrayArray *KeyValue::value_as<StylesV2::DoubleArrayArray>() const {
  return value_as_DoubleArrayArray();
}

struct KeyValueBuilder {
  typedef KeyValue Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(KeyValue::VT_KEY, key);
  }
  void add_value_type(StylesV2::Value value_type) {
    fbb_.AddElement<uint8_t>(KeyValue::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(KeyValue::VT_VALUE, value);
  }
  explicit KeyValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyValue> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyValue>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    StylesV2::Value value_type = StylesV2::Value_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  KeyValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyValue> CreateKeyValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    StylesV2::Value value_type = StylesV2::Value_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return StylesV2::CreateKeyValue(
      _fbb,
      key__,
      value_type,
      value);
}

struct Object FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIELDS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>> *fields() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>> *>(VT_FIELDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FIELDS) &&
           verifier.VerifyVector(fields()) &&
           verifier.VerifyVectorOfTables(fields()) &&
           verifier.EndTable();
  }
};

struct ObjectBuilder {
  typedef Object Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fields(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>>> fields) {
    fbb_.AddOffset(Object::VT_FIELDS, fields);
  }
  explicit ObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Object> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Object>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Object> CreateObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyValue>>> fields = 0) {
  ObjectBuilder builder_(_fbb);
  builder_.add_fields(fields);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Object> CreateObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::KeyValue>> *fields = nullptr) {
  auto fields__ = fields ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::KeyValue>>(*fields) : 0;
  return StylesV2::CreateObject(
      _fbb,
      fields__);
}

struct DeclarationTuple FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeclarationTupleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROPERTY_ID = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8,
    VT_FLAG = 10
  };
  uint8_t property_id() const {
    return GetField<uint8_t>(VT_PROPERTY_ID, 0);
  }
  StylesV2::Value value_type() const {
    return static_cast<StylesV2::Value>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const StylesV2::PoolString *value_as_PoolString() const {
    return value_type() == StylesV2::Value_PoolString ? static_cast<const StylesV2::PoolString *>(value()) : nullptr;
  }
  const StylesV2::Integer *value_as_Integer() const {
    return value_type() == StylesV2::Value_Integer ? static_cast<const StylesV2::Integer *>(value()) : nullptr;
  }
  const StylesV2::Double *value_as_Double() const {
    return value_type() == StylesV2::Value_Double ? static_cast<const StylesV2::Double *>(value()) : nullptr;
  }
  const StylesV2::Boolean *value_as_Boolean() const {
    return value_type() == StylesV2::Value_Boolean ? static_cast<const StylesV2::Boolean *>(value()) : nullptr;
  }
  const StylesV2::StringArray *value_as_StringArray() const {
    return value_type() == StylesV2::Value_StringArray ? static_cast<const StylesV2::StringArray *>(value()) : nullptr;
  }
  const StylesV2::IntegerArray *value_as_IntegerArray() const {
    return value_type() == StylesV2::Value_IntegerArray ? static_cast<const StylesV2::IntegerArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArray *value_as_DoubleArray() const {
    return value_type() == StylesV2::Value_DoubleArray ? static_cast<const StylesV2::DoubleArray *>(value()) : nullptr;
  }
  const StylesV2::Object *value_as_Object() const {
    return value_type() == StylesV2::Value_Object ? static_cast<const StylesV2::Object *>(value()) : nullptr;
  }
  const StylesV2::ObjectArray *value_as_ObjectArray() const {
    return value_type() == StylesV2::Value_ObjectArray ? static_cast<const StylesV2::ObjectArray *>(value()) : nullptr;
  }
  const StylesV2::IntegereArrayArray *value_as_IntegereArrayArray() const {
    return value_type() == StylesV2::Value_IntegereArrayArray ? static_cast<const StylesV2::IntegereArrayArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArrayArray *value_as_DoubleArrayArray() const {
    return value_type() == StylesV2::Value_DoubleArrayArray ? static_cast<const StylesV2::DoubleArrayArray *>(value()) : nullptr;
  }
  uint8_t flag() const {
    return GetField<uint8_t>(VT_FLAG, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PROPERTY_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyValue(verifier, value(), value_type()) &&
           VerifyField<uint8_t>(verifier, VT_FLAG, 1) &&
           verifier.EndTable();
  }
};

template<> inline const StylesV2::PoolString *DeclarationTuple::value_as<StylesV2::PoolString>() const {
  return value_as_PoolString();
}

template<> inline const StylesV2::Integer *DeclarationTuple::value_as<StylesV2::Integer>() const {
  return value_as_Integer();
}

template<> inline const StylesV2::Double *DeclarationTuple::value_as<StylesV2::Double>() const {
  return value_as_Double();
}

template<> inline const StylesV2::Boolean *DeclarationTuple::value_as<StylesV2::Boolean>() const {
  return value_as_Boolean();
}

template<> inline const StylesV2::StringArray *DeclarationTuple::value_as<StylesV2::StringArray>() const {
  return value_as_StringArray();
}

template<> inline const StylesV2::IntegerArray *DeclarationTuple::value_as<StylesV2::IntegerArray>() const {
  return value_as_IntegerArray();
}

template<> inline const StylesV2::DoubleArray *DeclarationTuple::value_as<StylesV2::DoubleArray>() const {
  return value_as_DoubleArray();
}

template<> inline const StylesV2::Object *DeclarationTuple::value_as<StylesV2::Object>() const {
  return value_as_Object();
}

template<> inline const StylesV2::ObjectArray *DeclarationTuple::value_as<StylesV2::ObjectArray>() const {
  return value_as_ObjectArray();
}

template<> inline const StylesV2::IntegereArrayArray *DeclarationTuple::value_as<StylesV2::IntegereArrayArray>() const {
  return value_as_IntegereArrayArray();
}

template<> inline const StylesV2::DoubleArrayArray *DeclarationTuple::value_as<StylesV2::DoubleArrayArray>() const {
  return value_as_DoubleArrayArray();
}

struct DeclarationTupleBuilder {
  typedef DeclarationTuple Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_property_id(uint8_t property_id) {
    fbb_.AddElement<uint8_t>(DeclarationTuple::VT_PROPERTY_ID, property_id, 0);
  }
  void add_value_type(StylesV2::Value value_type) {
    fbb_.AddElement<uint8_t>(DeclarationTuple::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(DeclarationTuple::VT_VALUE, value);
  }
  void add_flag(uint8_t flag) {
    fbb_.AddElement<uint8_t>(DeclarationTuple::VT_FLAG, flag, 0);
  }
  explicit DeclarationTupleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeclarationTuple> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeclarationTuple>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeclarationTuple> CreateDeclarationTuple(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t property_id = 0,
    StylesV2::Value value_type = StylesV2::Value_NONE,
    ::flatbuffers::Offset<void> value = 0,
    uint8_t flag = 0) {
  DeclarationTupleBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_flag(flag);
  builder_.add_value_type(value_type);
  builder_.add_property_id(property_id);
  return builder_.Finish();
}

struct Style FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StyleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DECLARATIONS = 4,
    VT_MEDIA = 6,
    VT_PSEUDO = 8,
    VT_PSEUDO_KEY = 10,
    VT_PSEUDO_VAL = 12,
    VT_SELECTOR = 14,
    VT_VARIABLES = 16
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *declarations() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *>(VT_DECLARATIONS);
  }
  uint8_t media() const {
    return GetField<uint8_t>(VT_MEDIA, 0);
  }
  uint8_t pseudo() const {
    return GetField<uint8_t>(VT_PSEUDO, 0);
  }
  const ::flatbuffers::Vector<const StylesV2::PseudoKey *> *pseudo_key() const {
    return GetPointer<const ::flatbuffers::Vector<const StylesV2::PseudoKey *> *>(VT_PSEUDO_KEY);
  }
  const ::flatbuffers::String *pseudo_val() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PSEUDO_VAL);
  }
  const ::flatbuffers::Vector<const StylesV2::Selector *> *selector() const {
    return GetPointer<const ::flatbuffers::Vector<const StylesV2::Selector *> *>(VT_SELECTOR);
  }
  const ::flatbuffers::Vector<const StylesV2::KeyValueString *> *variables() const {
    return GetPointer<const ::flatbuffers::Vector<const StylesV2::KeyValueString *> *>(VT_VARIABLES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DECLARATIONS) &&
           verifier.VerifyVector(declarations()) &&
           verifier.VerifyVectorOfTables(declarations()) &&
           VerifyField<uint8_t>(verifier, VT_MEDIA, 1) &&
           VerifyField<uint8_t>(verifier, VT_PSEUDO, 1) &&
           VerifyOffset(verifier, VT_PSEUDO_KEY) &&
           verifier.VerifyVector(pseudo_key()) &&
           VerifyOffset(verifier, VT_PSEUDO_VAL) &&
           verifier.VerifyString(pseudo_val()) &&
           VerifyOffset(verifier, VT_SELECTOR) &&
           verifier.VerifyVector(selector()) &&
           VerifyOffset(verifier, VT_VARIABLES) &&
           verifier.VerifyVector(variables()) &&
           verifier.EndTable();
  }
};

struct StyleBuilder {
  typedef Style Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_declarations(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>> declarations) {
    fbb_.AddOffset(Style::VT_DECLARATIONS, declarations);
  }
  void add_media(uint8_t media) {
    fbb_.AddElement<uint8_t>(Style::VT_MEDIA, media, 0);
  }
  void add_pseudo(uint8_t pseudo) {
    fbb_.AddElement<uint8_t>(Style::VT_PSEUDO, pseudo, 0);
  }
  void add_pseudo_key(::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::PseudoKey *>> pseudo_key) {
    fbb_.AddOffset(Style::VT_PSEUDO_KEY, pseudo_key);
  }
  void add_pseudo_val(::flatbuffers::Offset<::flatbuffers::String> pseudo_val) {
    fbb_.AddOffset(Style::VT_PSEUDO_VAL, pseudo_val);
  }
  void add_selector(::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::Selector *>> selector) {
    fbb_.AddOffset(Style::VT_SELECTOR, selector);
  }
  void add_variables(::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::KeyValueString *>> variables) {
    fbb_.AddOffset(Style::VT_VARIABLES, variables);
  }
  explicit StyleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Style> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Style>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Style> CreateStyle(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>> declarations = 0,
    uint8_t media = 0,
    uint8_t pseudo = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::PseudoKey *>> pseudo_key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pseudo_val = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::Selector *>> selector = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const StylesV2::KeyValueString *>> variables = 0) {
  StyleBuilder builder_(_fbb);
  builder_.add_variables(variables);
  builder_.add_selector(selector);
  builder_.add_pseudo_val(pseudo_val);
  builder_.add_pseudo_key(pseudo_key);
  builder_.add_declarations(declarations);
  builder_.add_pseudo(pseudo);
  builder_.add_media(media);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Style> CreateStyleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *declarations = nullptr,
    uint8_t media = 0,
    uint8_t pseudo = 0,
    const std::vector<StylesV2::PseudoKey> *pseudo_key = nullptr,
    const char *pseudo_val = nullptr,
    const std::vector<StylesV2::Selector> *selector = nullptr,
    const std::vector<StylesV2::KeyValueString> *variables = nullptr) {
  auto declarations__ = declarations ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>(*declarations) : 0;
  auto pseudo_key__ = pseudo_key ? _fbb.CreateVectorOfStructs<StylesV2::PseudoKey>(*pseudo_key) : 0;
  auto pseudo_val__ = pseudo_val ? _fbb.CreateString(pseudo_val) : 0;
  auto selector__ = selector ? _fbb.CreateVectorOfStructs<StylesV2::Selector>(*selector) : 0;
  auto variables__ = variables ? _fbb.CreateVectorOfStructs<StylesV2::KeyValueString>(*variables) : 0;
  return StylesV2::CreateStyle(
      _fbb,
      declarations__,
      media,
      pseudo,
      pseudo_key__,
      pseudo_val__,
      selector__,
      variables__);
}

struct Font FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FontBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FONT_FAMILY = 4,
    VT_SRC = 6
  };
  const ::flatbuffers::String *font_family() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FONT_FAMILY);
  }
  const ::flatbuffers::String *src() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SRC);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FONT_FAMILY) &&
           verifier.VerifyString(font_family()) &&
           VerifyOffset(verifier, VT_SRC) &&
           verifier.VerifyString(src()) &&
           verifier.EndTable();
  }
};

struct FontBuilder {
  typedef Font Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_font_family(::flatbuffers::Offset<::flatbuffers::String> font_family) {
    fbb_.AddOffset(Font::VT_FONT_FAMILY, font_family);
  }
  void add_src(::flatbuffers::Offset<::flatbuffers::String> src) {
    fbb_.AddOffset(Font::VT_SRC, src);
  }
  explicit FontBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Font> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Font>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Font> CreateFont(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> font_family = 0,
    ::flatbuffers::Offset<::flatbuffers::String> src = 0) {
  FontBuilder builder_(_fbb);
  builder_.add_src(src);
  builder_.add_font_family(font_family);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Font> CreateFontDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *font_family = nullptr,
    const char *src = nullptr) {
  auto font_family__ = font_family ? _fbb.CreateString(font_family) : 0;
  auto src__ = src ? _fbb.CreateString(src) : 0;
  return StylesV2::CreateFont(
      _fbb,
      font_family__,
      src__);
}

struct KeyframeAnimationPoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyframeAnimationPointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PERCENTAGE = 4,
    VT_DECLARATIONS = 6
  };
  float percentage() const {
    return GetField<float>(VT_PERCENTAGE, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *declarations() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *>(VT_DECLARATIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_PERCENTAGE, 4) &&
           VerifyOffset(verifier, VT_DECLARATIONS) &&
           verifier.VerifyVector(declarations()) &&
           verifier.VerifyVectorOfTables(declarations()) &&
           verifier.EndTable();
  }
};

struct KeyframeAnimationPointBuilder {
  typedef KeyframeAnimationPoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_percentage(float percentage) {
    fbb_.AddElement<float>(KeyframeAnimationPoint::VT_PERCENTAGE, percentage, 0.0f);
  }
  void add_declarations(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>> declarations) {
    fbb_.AddOffset(KeyframeAnimationPoint::VT_DECLARATIONS, declarations);
  }
  explicit KeyframeAnimationPointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyframeAnimationPoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyframeAnimationPoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyframeAnimationPoint> CreateKeyframeAnimationPoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float percentage = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>> declarations = 0) {
  KeyframeAnimationPointBuilder builder_(_fbb);
  builder_.add_declarations(declarations);
  builder_.add_percentage(percentage);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyframeAnimationPoint> CreateKeyframeAnimationPointDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float percentage = 0.0f,
    const std::vector<::flatbuffers::Offset<StylesV2::DeclarationTuple>> *declarations = nullptr) {
  auto declarations__ = declarations ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::DeclarationTuple>>(*declarations) : 0;
  return StylesV2::CreateKeyframeAnimationPoint(
      _fbb,
      percentage,
      declarations__);
}

struct KeyframeAnimation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyframeAnimationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_MEDIA = 6,
    VT_KEYFRAME_POINTS = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint8_t media() const {
    return GetField<uint8_t>(VT_MEDIA, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>> *keyframe_points() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>> *>(VT_KEYFRAME_POINTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_MEDIA, 1) &&
           VerifyOffset(verifier, VT_KEYFRAME_POINTS) &&
           verifier.VerifyVector(keyframe_points()) &&
           verifier.VerifyVectorOfTables(keyframe_points()) &&
           verifier.EndTable();
  }
};

struct KeyframeAnimationBuilder {
  typedef KeyframeAnimation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(KeyframeAnimation::VT_NAME, name);
  }
  void add_media(uint8_t media) {
    fbb_.AddElement<uint8_t>(KeyframeAnimation::VT_MEDIA, media, 0);
  }
  void add_keyframe_points(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>>> keyframe_points) {
    fbb_.AddOffset(KeyframeAnimation::VT_KEYFRAME_POINTS, keyframe_points);
  }
  explicit KeyframeAnimationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyframeAnimation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyframeAnimation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyframeAnimation> CreateKeyframeAnimation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint8_t media = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>>> keyframe_points = 0) {
  KeyframeAnimationBuilder builder_(_fbb);
  builder_.add_keyframe_points(keyframe_points);
  builder_.add_name(name);
  builder_.add_media(media);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyframeAnimation> CreateKeyframeAnimationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint8_t media = 0,
    const std::vector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>> *keyframe_points = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto keyframe_points__ = keyframe_points ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::KeyframeAnimationPoint>>(*keyframe_points) : 0;
  return StylesV2::CreateKeyframeAnimation(
      _fbb,
      name__,
      media,
      keyframe_points__);
}

struct PrimitiveCondition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PrimitiveConditionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEATURE = 4,
    VT_OPERATOR_ = 6,
    VT_VALUE_TYPE = 8,
    VT_VALUE = 10
  };
  uint8_t feature() const {
    return GetField<uint8_t>(VT_FEATURE, 0);
  }
  uint8_t operator_() const {
    return GetField<uint8_t>(VT_OPERATOR_, 0);
  }
  StylesV2::Value value_type() const {
    return static_cast<StylesV2::Value>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const StylesV2::PoolString *value_as_PoolString() const {
    return value_type() == StylesV2::Value_PoolString ? static_cast<const StylesV2::PoolString *>(value()) : nullptr;
  }
  const StylesV2::Integer *value_as_Integer() const {
    return value_type() == StylesV2::Value_Integer ? static_cast<const StylesV2::Integer *>(value()) : nullptr;
  }
  const StylesV2::Double *value_as_Double() const {
    return value_type() == StylesV2::Value_Double ? static_cast<const StylesV2::Double *>(value()) : nullptr;
  }
  const StylesV2::Boolean *value_as_Boolean() const {
    return value_type() == StylesV2::Value_Boolean ? static_cast<const StylesV2::Boolean *>(value()) : nullptr;
  }
  const StylesV2::StringArray *value_as_StringArray() const {
    return value_type() == StylesV2::Value_StringArray ? static_cast<const StylesV2::StringArray *>(value()) : nullptr;
  }
  const StylesV2::IntegerArray *value_as_IntegerArray() const {
    return value_type() == StylesV2::Value_IntegerArray ? static_cast<const StylesV2::IntegerArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArray *value_as_DoubleArray() const {
    return value_type() == StylesV2::Value_DoubleArray ? static_cast<const StylesV2::DoubleArray *>(value()) : nullptr;
  }
  const StylesV2::Object *value_as_Object() const {
    return value_type() == StylesV2::Value_Object ? static_cast<const StylesV2::Object *>(value()) : nullptr;
  }
  const StylesV2::ObjectArray *value_as_ObjectArray() const {
    return value_type() == StylesV2::Value_ObjectArray ? static_cast<const StylesV2::ObjectArray *>(value()) : nullptr;
  }
  const StylesV2::IntegereArrayArray *value_as_IntegereArrayArray() const {
    return value_type() == StylesV2::Value_IntegereArrayArray ? static_cast<const StylesV2::IntegereArrayArray *>(value()) : nullptr;
  }
  const StylesV2::DoubleArrayArray *value_as_DoubleArrayArray() const {
    return value_type() == StylesV2::Value_DoubleArrayArray ? static_cast<const StylesV2::DoubleArrayArray *>(value()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEATURE, 1) &&
           VerifyField<uint8_t>(verifier, VT_OPERATOR_, 1) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const StylesV2::PoolString *PrimitiveCondition::value_as<StylesV2::PoolString>() const {
  return value_as_PoolString();
}

template<> inline const StylesV2::Integer *PrimitiveCondition::value_as<StylesV2::Integer>() const {
  return value_as_Integer();
}

template<> inline const StylesV2::Double *PrimitiveCondition::value_as<StylesV2::Double>() const {
  return value_as_Double();
}

template<> inline const StylesV2::Boolean *PrimitiveCondition::value_as<StylesV2::Boolean>() const {
  return value_as_Boolean();
}

template<> inline const StylesV2::StringArray *PrimitiveCondition::value_as<StylesV2::StringArray>() const {
  return value_as_StringArray();
}

template<> inline const StylesV2::IntegerArray *PrimitiveCondition::value_as<StylesV2::IntegerArray>() const {
  return value_as_IntegerArray();
}

template<> inline const StylesV2::DoubleArray *PrimitiveCondition::value_as<StylesV2::DoubleArray>() const {
  return value_as_DoubleArray();
}

template<> inline const StylesV2::Object *PrimitiveCondition::value_as<StylesV2::Object>() const {
  return value_as_Object();
}

template<> inline const StylesV2::ObjectArray *PrimitiveCondition::value_as<StylesV2::ObjectArray>() const {
  return value_as_ObjectArray();
}

template<> inline const StylesV2::IntegereArrayArray *PrimitiveCondition::value_as<StylesV2::IntegereArrayArray>() const {
  return value_as_IntegereArrayArray();
}

template<> inline const StylesV2::DoubleArrayArray *PrimitiveCondition::value_as<StylesV2::DoubleArrayArray>() const {
  return value_as_DoubleArrayArray();
}

struct PrimitiveConditionBuilder {
  typedef PrimitiveCondition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feature(uint8_t feature) {
    fbb_.AddElement<uint8_t>(PrimitiveCondition::VT_FEATURE, feature, 0);
  }
  void add_operator_(uint8_t operator_) {
    fbb_.AddElement<uint8_t>(PrimitiveCondition::VT_OPERATOR_, operator_, 0);
  }
  void add_value_type(StylesV2::Value value_type) {
    fbb_.AddElement<uint8_t>(PrimitiveCondition::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(PrimitiveCondition::VT_VALUE, value);
  }
  explicit PrimitiveConditionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PrimitiveCondition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PrimitiveCondition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PrimitiveCondition> CreatePrimitiveCondition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t feature = 0,
    uint8_t operator_ = 0,
    StylesV2::Value value_type = StylesV2::Value_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  PrimitiveConditionBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_value_type(value_type);
  builder_.add_operator_(operator_);
  builder_.add_feature(feature);
  return builder_.Finish();
}

struct CompoundCondition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CompoundConditionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONDITIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>> *conditions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>> *>(VT_CONDITIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONDITIONS) &&
           verifier.VerifyVector(conditions()) &&
           verifier.VerifyVectorOfTables(conditions()) &&
           verifier.EndTable();
  }
};

struct CompoundConditionBuilder {
  typedef CompoundCondition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_conditions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>>> conditions) {
    fbb_.AddOffset(CompoundCondition::VT_CONDITIONS, conditions);
  }
  explicit CompoundConditionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CompoundCondition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CompoundCondition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CompoundCondition> CreateCompoundCondition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>>> conditions = 0) {
  CompoundConditionBuilder builder_(_fbb);
  builder_.add_conditions(conditions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CompoundCondition> CreateCompoundConditionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::Condition>> *conditions = nullptr) {
  auto conditions__ = conditions ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::Condition>>(*conditions) : 0;
  return StylesV2::CreateCompoundCondition(
      _fbb,
      conditions__);
}

struct Condition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConditionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8
  };
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  StylesV2::ConditionValue value_type() const {
    return static_cast<StylesV2::ConditionValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const StylesV2::PrimitiveCondition *value_as_PrimitiveCondition() const {
    return value_type() == StylesV2::ConditionValue_PrimitiveCondition ? static_cast<const StylesV2::PrimitiveCondition *>(value()) : nullptr;
  }
  const StylesV2::CompoundCondition *value_as_CompoundCondition() const {
    return value_type() == StylesV2::ConditionValue_CompoundCondition ? static_cast<const StylesV2::CompoundCondition *>(value()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyConditionValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const StylesV2::PrimitiveCondition *Condition::value_as<StylesV2::PrimitiveCondition>() const {
  return value_as_PrimitiveCondition();
}

template<> inline const StylesV2::CompoundCondition *Condition::value_as<StylesV2::CompoundCondition>() const {
  return value_as_CompoundCondition();
}

struct ConditionBuilder {
  typedef Condition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(Condition::VT_TYPE, type, 0);
  }
  void add_value_type(StylesV2::ConditionValue value_type) {
    fbb_.AddElement<uint8_t>(Condition::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(Condition::VT_VALUE, value);
  }
  explicit ConditionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Condition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Condition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Condition> CreateCondition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t type = 0,
    StylesV2::ConditionValue value_type = StylesV2::ConditionValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  ConditionBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_value_type(value_type);
  builder_.add_type(type);
  return builder_.Finish();
}

struct Media FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MediaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CONDITIONS = 6
  };
  uint8_t id() const {
    return GetField<uint8_t>(VT_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>> *conditions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>> *>(VT_CONDITIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ID, 1) &&
           VerifyOffset(verifier, VT_CONDITIONS) &&
           verifier.VerifyVector(conditions()) &&
           verifier.VerifyVectorOfTables(conditions()) &&
           verifier.EndTable();
  }
};

struct MediaBuilder {
  typedef Media Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint8_t id) {
    fbb_.AddElement<uint8_t>(Media::VT_ID, id, 0);
  }
  void add_conditions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>>> conditions) {
    fbb_.AddOffset(Media::VT_CONDITIONS, conditions);
  }
  explicit MediaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Media> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Media>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Media> CreateMedia(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Condition>>> conditions = 0) {
  MediaBuilder builder_(_fbb);
  builder_.add_conditions(conditions);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Media> CreateMediaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t id = 0,
    const std::vector<::flatbuffers::Offset<StylesV2::Condition>> *conditions = nullptr) {
  auto conditions__ = conditions ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::Condition>>(*conditions) : 0;
  return StylesV2::CreateMedia(
      _fbb,
      id,
      conditions__);
}

struct StyleSheet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StyleSheetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FONTS = 4,
    VT_KEYFRAMES = 6,
    VT_MEDIAS = 8,
    VT_STYLES = 10,
    VT_STRING_POOL = 12,
    VT_DESIGN_WIDTH = 14,
    VT_ALLOW_INHERIT = 16
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Font>> *fonts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Font>> *>(VT_FONTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>> *keyframes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>> *>(VT_KEYFRAMES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Media>> *medias() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Media>> *>(VT_MEDIAS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Style>> *styles() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Style>> *>(VT_STYLES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *string_pool() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_STRING_POOL);
  }
  uint16_t design_width() const {
    return GetField<uint16_t>(VT_DESIGN_WIDTH, 0);
  }
  bool allow_inherit() const {
    return GetField<uint8_t>(VT_ALLOW_INHERIT, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FONTS) &&
           verifier.VerifyVector(fonts()) &&
           verifier.VerifyVectorOfTables(fonts()) &&
           VerifyOffset(verifier, VT_KEYFRAMES) &&
           verifier.VerifyVector(keyframes()) &&
           verifier.VerifyVectorOfTables(keyframes()) &&
           VerifyOffset(verifier, VT_MEDIAS) &&
           verifier.VerifyVector(medias()) &&
           verifier.VerifyVectorOfTables(medias()) &&
           VerifyOffset(verifier, VT_STYLES) &&
           verifier.VerifyVector(styles()) &&
           verifier.VerifyVectorOfTables(styles()) &&
           VerifyOffset(verifier, VT_STRING_POOL) &&
           verifier.VerifyVector(string_pool()) &&
           verifier.VerifyVectorOfStrings(string_pool()) &&
           VerifyField<uint16_t>(verifier, VT_DESIGN_WIDTH, 2) &&
           VerifyField<uint8_t>(verifier, VT_ALLOW_INHERIT, 1) &&
           verifier.EndTable();
  }
};

struct StyleSheetBuilder {
  typedef StyleSheet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fonts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Font>>> fonts) {
    fbb_.AddOffset(StyleSheet::VT_FONTS, fonts);
  }
  void add_keyframes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>>> keyframes) {
    fbb_.AddOffset(StyleSheet::VT_KEYFRAMES, keyframes);
  }
  void add_medias(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Media>>> medias) {
    fbb_.AddOffset(StyleSheet::VT_MEDIAS, medias);
  }
  void add_styles(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Style>>> styles) {
    fbb_.AddOffset(StyleSheet::VT_STYLES, styles);
  }
  void add_string_pool(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> string_pool) {
    fbb_.AddOffset(StyleSheet::VT_STRING_POOL, string_pool);
  }
  void add_design_width(uint16_t design_width) {
    fbb_.AddElement<uint16_t>(StyleSheet::VT_DESIGN_WIDTH, design_width, 0);
  }
  void add_allow_inherit(bool allow_inherit) {
    fbb_.AddElement<uint8_t>(StyleSheet::VT_ALLOW_INHERIT, static_cast<uint8_t>(allow_inherit), 0);
  }
  explicit StyleSheetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StyleSheet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StyleSheet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StyleSheet> CreateStyleSheet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Font>>> fonts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>>> keyframes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Media>>> medias = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StylesV2::Style>>> styles = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> string_pool = 0,
    uint16_t design_width = 0,
    bool allow_inherit = false) {
  StyleSheetBuilder builder_(_fbb);
  builder_.add_string_pool(string_pool);
  builder_.add_styles(styles);
  builder_.add_medias(medias);
  builder_.add_keyframes(keyframes);
  builder_.add_fonts(fonts);
  builder_.add_design_width(design_width);
  builder_.add_allow_inherit(allow_inherit);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StyleSheet> CreateStyleSheetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StylesV2::Font>> *fonts = nullptr,
    const std::vector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>> *keyframes = nullptr,
    const std::vector<::flatbuffers::Offset<StylesV2::Media>> *medias = nullptr,
    const std::vector<::flatbuffers::Offset<StylesV2::Style>> *styles = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *string_pool = nullptr,
    uint16_t design_width = 0,
    bool allow_inherit = false) {
  auto fonts__ = fonts ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::Font>>(*fonts) : 0;
  auto keyframes__ = keyframes ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::KeyframeAnimation>>(*keyframes) : 0;
  auto medias__ = medias ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::Media>>(*medias) : 0;
  auto styles__ = styles ? _fbb.CreateVector<::flatbuffers::Offset<StylesV2::Style>>(*styles) : 0;
  auto string_pool__ = string_pool ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*string_pool) : 0;
  return StylesV2::CreateStyleSheet(
      _fbb,
      fonts__,
      keyframes__,
      medias__,
      styles__,
      string_pool__,
      design_width,
      allow_inherit);
}

inline bool VerifyValue(::flatbuffers::Verifier &verifier, const void *obj, Value type) {
  switch (type) {
    case Value_NONE: {
      return true;
    }
    case Value_PoolString: {
      auto ptr = reinterpret_cast<const StylesV2::PoolString *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_Integer: {
      auto ptr = reinterpret_cast<const StylesV2::Integer *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_Double: {
      auto ptr = reinterpret_cast<const StylesV2::Double *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_Boolean: {
      auto ptr = reinterpret_cast<const StylesV2::Boolean *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_StringArray: {
      auto ptr = reinterpret_cast<const StylesV2::StringArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_IntegerArray: {
      auto ptr = reinterpret_cast<const StylesV2::IntegerArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_DoubleArray: {
      auto ptr = reinterpret_cast<const StylesV2::DoubleArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_Object: {
      auto ptr = reinterpret_cast<const StylesV2::Object *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_ObjectArray: {
      auto ptr = reinterpret_cast<const StylesV2::ObjectArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_IntegereArrayArray: {
      auto ptr = reinterpret_cast<const StylesV2::IntegereArrayArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value_DoubleArrayArray: {
      auto ptr = reinterpret_cast<const StylesV2::DoubleArrayArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyValue(
        verifier,  values->Get(i), types->GetEnum<Value>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyConditionValue(::flatbuffers::Verifier &verifier, const void *obj, ConditionValue type) {
  switch (type) {
    case ConditionValue_NONE: {
      return true;
    }
    case ConditionValue_PrimitiveCondition: {
      auto ptr = reinterpret_cast<const StylesV2::PrimitiveCondition *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConditionValue_CompoundCondition: {
      auto ptr = reinterpret_cast<const StylesV2::CompoundCondition *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyConditionValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyConditionValue(
        verifier,  values->Get(i), types->GetEnum<ConditionValue>(i))) {
      return false;
    }
  }
  return true;
}

inline const StylesV2::StyleSheet *GetStyleSheet(const void *buf) {
  return ::flatbuffers::GetRoot<StylesV2::StyleSheet>(buf);
}

inline const StylesV2::StyleSheet *GetSizePrefixedStyleSheet(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<StylesV2::StyleSheet>(buf);
}

inline bool VerifyStyleSheetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<StylesV2::StyleSheet>(nullptr);
}

inline bool VerifySizePrefixedStyleSheetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<StylesV2::StyleSheet>(nullptr);
}

inline void FinishStyleSheetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StylesV2::StyleSheet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStyleSheetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StylesV2::StyleSheet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace StylesV2

#endif  // FLATBUFFERS_GENERATED_STYLESHEETV2_STYLESV2_H_
