/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParseOptions {
  platformString: string
  isEnableNesting?: boolean
}
export interface ParseResult {
  code: string
}
export function parse(component: string, styles: Array<string>, options: ParseOptions): ParseResult
