/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OutputOptions {
  isBin?: boolean
}
export interface ParseOptions {
  platformString: string
  designWidth?: number
  output?: OutputOptions
}
export interface ParseResult {
  code?: string
  buffer?: Buffer
}
export declare function parse(styles: Array<string>, options: ParseOptions): ParseResult
