/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParseOptions {
  platformString: string
  isEnableNesting?: boolean
}
export interface ParseResult {
  code: string
  cssVariables?: string
}
export function parse(component: string, styles: Array<string>, options: ParseOptions): ParseResult
export function combineCssVariables(variables: Array<string>): string | null
